[package]
name = "FerrixOX"
version = "0.1.0"
authors = ["Constantin Bogdan-Teodor"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.6.1"
lazy_static = "1.4"
spin = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
